### ISSUE TITLE
Starting a service during image build / docker file, hangs

### ISSUE THREAD

**Issue by punowo** [gdraheim/docker-systemctl-replacement#156]
Hello. 
I'm trying to build an image that I can use as a development environment. I'm on WSL. The idea would be to just docker compose up -d, have the source code in WSL and then build and run the software. Currently calling systemctl start just gets stuck.

The dockerfile is: 
```
FROM  --platform=linux/amd64 almalinux:9-minimal
ENV container docker
USER root:root

RUN microdnf -y update \
    && microdnf -y install --nodocs python3 \
    && microdnf -y clean all \
    && rm -rf /var/cache/yum 

ADD https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py /usr/local/sbin/systemctl
RUN chmod +x /usr/local/sbin/systemctl

RUN echo -e "[mongodb-org-6.0]\nname=MongoDB Repository \nbaseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/6.0/x86_64/ \ngpgcheck=1 \nenabled=1 \ngpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc" > /etc/yum.repos.d/mongodb-org-6.0.repo

RUN microdnf -y update \
    && microdnf -y install --nodocs nano vim-minimal mongodb-org nginx procps-ng gcc python3 tar which \
    && microdnf -y clean all \
    && rm -rf /var/cache/yum 
RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash


RUN systemctl start nginx -vvv
RUN systemctl start mongod &

RUN mkdir -p /data/db
RUN chmod -R 777 /data/db
VOLUME [ "/data/db" ]
EXPOSE 27017

RUN . ~/.nvm/nvm.sh && nvm install --lts

EXPOSE 80

COPY docker-entrypoint.sh /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"]
ENTRYPOINT ["docker-entrypoint.sh"
```

docker-compose.yml
```
services:
  application:
    build: .
    privileged: true
    container_name: application
    ports:
      - 27017:27017
      - 80:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /mnt/application/data/db:/data/db:rw
```
docker-entrypoint.sh
```
#!/usr/bin/env bash

tail -f /dev/null
```

Here are some screenshots.
![Screenshot_1](https://user-images.githubusercontent.com/96526435/233320620-6c89f8bb-162b-4ce8-9620-d50660fbcc17.png)
![Screenshot_2](https://user-images.githubusercontent.com/96526435/233320645-c91cb32f-d3cb-43ae-825e-61a29a334973.png)
