### ISSUE TITLE
ExecStartPre control process exited

### ISSUE THREAD

**Issue by teake** [gdraheim/docker-systemctl-replacement#91]
Hi, first of thanks for the nice systemctl replacement!

Unfortunately I cannot get it to work in my Ansible playbook. I'm hoping to install PostgreSQL, but am running into a `ERROR:systemctl:the ExecStartPre control process exited` error.

Here's my Dockerfile:

```dockerfile
FROM centos:7

ADD https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py /usr/local/sbin/systemctl
RUN chmod +x /usr/local/sbin/systemctl
```
and here's my playbook:
```yml
- hosts: centos_container
  connection: docker
  tasks:
    - name: Install postgress
      block:
        - package:
            name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
            state: present
        - package:
            name: postgresql12-server
            state: present
        - command:
            cmd: /usr/pgsql-12/bin/postgresql-12-setup initdb
            creates: /var/lib/pgsql/12/data
        - service:
            name: postgresql-12
            state: started
```
Then doing 
```console
$ ansible-playbook -i centos_container, site.yml
```
(here `centos_container` is a container of an image built with the above Dockerfile, and the contents of `site.yml` is given above) will result in a fatal Ansible error with the message 

```
Unable to start service postgresql-12: ERROR:systemctl:the ExecStartPre control process exited with error code
```

Any help would greatly be appreciated!
